name: Experience

on:
  workflow_dispatch:

  schedule:
    - cron: 17 */6 * * *

env:
  TG_TOKEN: ${{ secrets.TG_TOKEN }}
  TG_CHATID: ${{ secrets.TG_CHATID }}

jobs:
  misc:
    name: Miscellaneous Sites
    runs-on: ubuntu-latest
    steps:
      - name: Sleep Random Time
        run: sleep $(shuf -i 10-60 -n 1)
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install dependencies
        run: python -m pip install --upgrade requests pyaes 
      - name: Hostloc Experience
        env:
          HOSTLOC_USERNAME: ${{ secrets.HOSTLOC_USERNAME }}
          HOSTLOC_PASSWORD: ${{ secrets.HOSTLOC_PASSWORD }}
        run: python Experience/hostloc.py || echo "HOSTLOC_FAIL=true" >> $GITHUB_ENV
      - name: Notify
        if: env.BYZH_FAIL || env.HOSTLOC_FAIL
        run: |
          [ $HOSTLOC_FAIL ] && python Notify.py 'Hostloc'
  
  epic_free_games:
    name: Epic Claimer
    runs-on: ubuntu-latest
    steps:
      - name: Sleep Random Time
        run: sleep $(shuf -i 10-60 -n 1)
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: lts/*
      - name: Clone
        run: git clone --depth 1 https://github.com/Revadike/epicgames-freebies-claimer Experience
      - name: Experience
        id: epic_experience
        env:
          EPIC_AUTH: ${{ secrets.EPIC_AUTH }}
        run: |
          cd Experience && npm install
          echo $EPIC_AUTH > data/device_auths.json
          mv data/config.example.json data/config.json
          sed -i 's/"loop": true/"loop": false/g' data/config.json
          npm start || echo "::set-output name=status::Error"
      - uses: actions/checkout@v2
        if: steps.epic_experience.outputs.status == 'Error'
      - name: Set Python
        if: steps.epic_experience.outputs.status == 'Error'
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Notify
        if: steps.epic_experience.outputs.status == 'Error'
        run: pip install requests && python Notify.py 'Epic'

  epicgames-claimer:
    name: epicgames-claimer
    runs-on: ubuntu-latest
    steps:
      - name: Sleep Random Time
        run: sleep $(shuf -i 10-60 -n 1)
      - name: Set Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Clone
        run: git clone --depth 1 https://github.com/luminoleon/epicgames-claimer Experience
             pip3 install -r Experience/requirements.txt
             sudo sh install_dependencies.sh
      - name: Experience
        id: Experience
        env:
          EPIC_MAIL: ${{ secrets.EPIC_MAIL }}
          EPIC_PASS: ${{ secrets.EPIC_PASS }}
      - name: main
        run: python main.py  -u $EPIC_MAIL -p $EPIC_PASS

  521pojie:
    name: 52Pojie Experience
    runs-on: ubuntu-latest
    steps:
      - name: Sleep Random Time
        run: sleep $(shuf -i 10-60 -n 1)
      - name: Set Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install dependencies
        run: |
          git clone --depth 1 https://github.com/mengshouer/CheckinBox Experience
          pip3 install -r Experience/requirements.txt
      - name: Experience
        id: pojie_experience
        env:
          cookie_52pj: ${{ secrets.PJ_COOKIE }}
        run: |
          python Experience/Checkin52pj/Checkin52pjForSCF.py > msg && cat msg
          [[ $(grep '失效|出错' msg) ]] && echo "::set-output name=status::Error" || true
      - uses: actions/checkout@v2
        if: steps.pojie_experience.outputs.status == 'Error'
      - name: Notify
        if: steps.pojie_experience.outputs.status == 'Error'
        run: python Notify.py '吾爱破解'

  freenom:
    runs-on: ubuntu-latest
    name: Freenom Extend
    steps:
      - name: Sleep Random Time
        run: sleep $(shuf -i 10-60 -n 1)
      - name: Clone
        run: git clone --depth 1 https://github.com/luolongfei/freenom Experience
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.2'
      - name: Setting
        run: |
          cd Experience && cp .env.example .env
          sed -i "s/^FREENOM_USERNAME=.*$/FREENOM_USERNAME='${{ secrets.FREENOM_USERNAME }}'/" .env
          sed -i "s/^FREENOM_PASSWORD=.*$/FREENOM_PASSWORD='${{ secrets.FREENOM_PASSWORD }}'/" .env
          sed -i "s/^MAIL_ENABLE=.*$/MAIL_ENABLE=false/" .env
          sed -i "s/^TELEGRAM_CHAT_ID=.*$/TELEGRAM_CHAT_ID='${{ secrets.TG_CHATID }}'/" .env
          sed -i "s/^TELEGRAM_BOT_TOKEN=.*$/TELEGRAM_BOT_TOKEN='${{ secrets.TG_TOKEN }}'/" .env
          sed -i "s/^TELEGRAM_BOT_ENABLE=.*$/TELEGRAM_BOT_ENABLE=true/" .env
          sed -i "s/^NOTICE_FREQ=.*$/NOTICE_FREQ=0/" .env
          sed -i "s/^ON_GITHUB_ACTIONS=.*$/ON_GITHUB_ACTIONS=true/" .env
      - name: Run
        run: cd Experience && php run
